### ISSUE TITLE
FR: nightly golang sidecar

### ISSUE THREAD

**Issue by gattytto** [che-dockerfiles/che-sidecar-go#20]
golang is 1.15alpha1 and latest gopls is @master, ms-vscode golang extension also has a separate nightly vsix. if we could have a :nightly version of the golang extension just as we have a theia:next version of theia, this could be very useful for future-proofing the standard sidecar and test new features (or make stuff that is very cutting edge) without having to go out of che.

**Comment by ericwill** [comment]
Is this something you'd be interested in setting up? I'd be happy to review PR's + provide feedback, but I don't have the time to develop it on my own.

**Comment by gattytto** [comment]
yes
